MOD THREE/little_esty_shop_bulk_discounts/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :merchant do
    resources :dashboard, only: [:index]
    resources :items, except: [:destroy]
    resources :item_status, only: [:update]
    resources :invoices, only: [:index, :show, :update]
    resources :bulk_discounts 
  end

  namespace :admin do
    resources :dashboard, only: [:index]
    resources :merchants, except: [:destroy]
    resources :merchant_status, only: [:update]
    resources :invoices, except: [:new, :destroy]
  end

end
  

    

MOD THREE/little_esty_shop_bulk_discounts/app/models/item.rb
class Item < ApplicationRecord
  validates_presence_of :name,
                        :description,
                        :unit_price,
                        :merchant_id

  has_many :invoice_items
  has_many :invoices, through: :invoice_items
  belongs_to :merchant

  enum status: [:disabled, :enabled]

  def best_day
    invoices
    .joins(:invoice_items)
    .where('invoices.status = 2')
    .select('invoices.*, sum(invoice_items.unit_price * invoice_items.quantity) as money')
    .group(:id)
    .order("money desc", "created_at desc")
    .first&.created_at&.to_date
  end
end

MOD THREE/little_esty_shop_bulk_discounts/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item_and_merchant, only: [:show, :edit, :update]
  before_action :find_merchant, only: [:new, :create, :index]

  def index
    @enabled_items = @merchant.items.where(status: 1)
    @disabled_items = @merchant.items.where(status: 0)
  end

  def show

  end

  def edit

  end

  def update
    if @item.update(item_params)
      flash.notice = "Succesfully Updated Item Info!"
      redirect_to merchant_item_path(@merchant, @item)
    else
      flash.notice = "All fields must be completed, get your act together."
      redirect_to edit_merchant_item_path(@merchant, @item)
    end
  end

  def new

  end

  def create
    Item.create!(name: params[:name],
                description: params[:description],
                unit_price: params[:unit_price],
                id: find_new_id, merchant: @merchant)
    redirect_to merchant_items_path(@merchant)
  end

  private
  def item_params
    params.require(:item).permit(:name, :description, :unit_price, :merchant_id)
  end

  def find_item_and_merchant
    @item = Item.find(params[:id])
    @merchant = Merchant.find(params[:merchant_id])
  end

  def find_merchant
    @merchant = Merchant.find(params[:merchant_id])
  end

  def find_new_id
    Item.last.id + 1
  end
end

MOD THREE/little_esty_shop_bulk_discounts/app/views/items/_form.html.erb
<%= form_with model: model, method: method, url: url, class: 'merchant_item_form', local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br/><br/>
  <%= f.label :description %>
  <%= f.text_field :description %><br/><br/>
  <%= f.label :unit_price %>
  <%= f.text_field :unit_price %><br/><br/>
  <%= f.submit 'Submit'%>
<% end %>

MOD THREE/little_esty_shop_bulk_discounts/app/views/items/edit.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <p class="navbar-text"><%= @merchant.name %></p>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Dashboard', merchant_dashboard_index_path, style: 'pull-right' %>
      <%= link_to 'My Items', merchant_items_path(@merchant), style: 'pull-right' %>
      <%= link_to 'My Invoices', merchant_invoices_path(@merchant), style: 'pull-right' %></li>
    </ul>
  </nav>
</div>

<%= render partial: 'form', locals: { method: :patch, url: merchant_item_path(@merchant, @item), class: 'merchant_item_form', local: true, model: @item} %>

MOD THREE/little_esty_shop_bulk_discounts/app/views/items/index.html.erb
<div class="nav-container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <p class="navbar-text"><%= @merchant.name %></p>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Dashboard', merchant_dashboard_index_path, style: 'pull-right' %>
      <%= link_to 'My Items', merchant_items_path(@merchant), style: 'pull-right' %>
      <%= link_to 'My Invoices', merchant_invoices_path(@merchant), style: 'pull-right' %></li>
    </ul>
  </nav>
</div>

<body>
  <div class="row">
    <p class='col-12'>My Items</p>
  </div>

  <p><%= link_to "Create New Item", new_merchant_item_path(@merchant) %></p>
    
  <div class="row">
    <p class='mr-auto col-sm-5'>Enabled Items</p>
    <p class='ml-auto col-sm-5'>Top Items</p>
  </div>

  <ul class='mr-auto col-sm-4'>
    <section id="enabled">
      <% @enabled_items.each do |item| %>
        <section id="item-<%= item.id %>">
          <li><%= link_to "#{item.name}", merchant_item_path(@merchant, item) %></li>
          <%= button_to "Disable", merchant_item_status_path(@merchant, item), method: :patch, params: {status: "disabled"} %>
        </section>
      <% end %>
    </section>
  </ul>
  
  <div class="row">
    <p class='mr-auto col-sm-5'>Disabled Merchants</p>
  </div>
  
  <ul class='mr-auto col-sm-4'>
    <section id="disabled">
      <% @disabled_items.each do |item| %>
        <section id="item-<%= item.id %>">
          <li><%= link_to "#{item.name}", merchant_item_path(@merchant, item) %></li>
          <%= button_to "Enable", merchant_item_status_path(@merchant, item), method: :patch, params: {status: "enabled"} %>
        </section>
      <% end %>
    </section>
  </ul>
  
  <ul class='ml-auto col-sm-4'>
  <section id="top_5">
    <% @merchant.top_5_items.each do |item| %>
      <li><%= link_to "#{item.name}", merchant_item_path(@merchant, item)  %> -
        $<%= item.total_revenue %> in sales</li>
      <p> Top selling date for <%= item.name %> was <%= item.best_day %> </p>
    <% end %>
  </section>
</body>

MOD THREE/little_esty_shop_bulk_discounts/app/views/items/new.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <p class="navbar-text"><%= @merchant.name %></p>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Dashboard', merchant_dashboard_index_path, style: 'pull-right' %>
      <%= link_to 'My Items', merchant_items_path(@merchant), style: 'pull-right' %>
      <%= link_to 'My Invoices', merchant_invoices_path(@merchant), style: 'pull-right' %></li>
    </ul>
  </nav>
</div>

<%= render partial: 'form', locals: { method: :post, url: merchant_items_path(@merchant, @item), class: 'merchant_item_form', local: true, model: nil } %>

MOD THREE/little_esty_shop_bulk_discounts/app/views/items/show.html.erb
<div class="nav-container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <p class="navbar-text"><%= @merchant.name %></p>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Dashboard', merchant_dashboard_index_path, style: 'pull-right' %>
      <%= link_to 'My Items', merchant_items_path(@merchant), style: 'pull-right' %>
      <%= link_to 'My Invoices', merchant_invoices_path(@merchant), style: 'pull-right' %></li>
    </ul>
  </nav>
</div>

<body>
  <div class="row">
    <p class='col-12'><%= @item.name %></p>
  </div>


  <p><%= @item.description %></p><br/>

  <p>Price: $<%= @item.unit_price %></p>

  <strong><%= link_to "Update Item", edit_merchant_item_path(@merchant, @item) %></strong>

</body>