MOD THREE/viewing_party_lite/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'landing_page#index'

  resources :users, only:[:show, :new, :create] do
    resources :discoveries, only:[:index]
    resources :movies, only:[:index, :show] do
      resources :view_parties, only: [:new, :create]
    end

  end
end

MOD THREE/viewing_party_lite/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MOD THREE/viewing_party_lite/app/models/party_guest.rb
class PartyGuest < ApplicationRecord
  belongs_to :view_party

  validates :view_party_id, presence: true
  validates :guest_id, presence: true
end

MOD THREE/viewing_party_lite/app/models/user.rb
class User < ApplicationRecord
  has_many :view_parties

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

MOD THREE/viewing_party_lite/app/models/view_party.rb
class ViewParty < ApplicationRecord
  belongs_to :user
  has_many :party_guests

  validates :date, presence: true
  validates :time, presence: true
  validates :duration, presence: true, numericality: true
end

MOD THREE/viewing_party_lite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

MOD THREE/viewing_party_lite/app/controllers/discoveries_controller.rb
class DiscoveriesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end
end

MOD THREE/viewing_party_lite/app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
    @users = User.all
  end
end

MOD THREE/viewing_party_lite/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @user = User.find(params[:user_id])

    if params[:q] != "top%20rated"
      keyword = params[:q]
      @search_results = MovieSearchFacade.movie_search(keyword)
    else
      @search_results = []
      @top_rated = TopRatedMoviesFacade.top_20_rated_movies
    end
  end

  def show
    @user = User.find(params[:user_id])
    movie_id = params[:id]
    @movie = TMDBService.get_movie_by_id(movie_id)
    @cast = MovieCastFacade.cast(movie_id)
    @reviews = MovieReviewFacade.movie_review(movie_id)

  end
end

MOD THREE/viewing_party_lite/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
   
    view_parties = @user.view_parties
    movie_ids = view_parties.map do |party|
      party[:movie_id]
    end

    party_guest_ids = view_parties.map do |party|
      party.party_guests.pluck(:guest_id)
    end.flatten

    @party_guests = party_guest_ids.map do |guest|
      User.find(guest).name
    end

    @movies = movie_ids.map do |movie_id|
      TMDBService.get_movie_by_id(movie_id)
    end
  end
  
  def new
    User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    elsif @user.name == "" || @user.email == "" 
      redirect_to new_user_path, notice: "Field can't be blank."
    else 
      redirect_to new_user_path, notice: "Enter valid name and email."
    end
  end

  private
  
  def user_params
    params.permit(:name, :email)
  end
end

MOD THREE/viewing_party_lite/app/controllers/view_parties_controller.rb
class ViewPartiesController < ApplicationController
  def new
    @users = User.where("id != ?", params[:user_id])
    @user = User.find(params[:user_id])
    movie_id = params[:movie_id]
    @movie = TMDBService.get_movie_by_id(movie_id)
    view_party = ViewParty.new
  end

  def create
    user = User.find(params[:user_id])
    movie_id = params[:movie_id]
    view_party = user.view_parties.new(new_view_party_params)

    if view_party.save
      guests = params[:guest].reject! {|guest| guest.empty?}
      guests.map do |guest|
        view_party.party_guests.create(guest_id: guest.to_i)
      end
      redirect_to user_path(user.id)
    else
      redirect_to new_user_movie_view_party_path(user.id, movie_id), notice: "Invalid input"
    end
  end

  private
  def new_view_party_params
    params.permit(:duration, :date, :time, :movie_id)
  end
end

MOD THREE/viewing_party_lite/app/helpers/application_helper.rb
module ApplicationHelper
end

MOD THREE/viewing_party_lite/app/views/movies/index.html.erb
<h2 hidden>Movie Results Page</h2>

<%= button_to "Return to Discover Movies",  user_discoveries_path(@user.id), method: :get %>

<% if @search_results != [] %>
  <h2> Movie Search Results </h2>

  <section id="movie_search_results">
    <table>
      <caption hidden>Movie Results</caption>
      <tr>
        <th>Title</th>
        <th>Vote Avg</th>
      </tr>
      <% @search_results.each do |movie| %>
        <tr>
          <td><%= link_to movie.title, user_movie_path(@user.id, movie.id) %></td>
          <td><%= movie.vote_avg %></td>
        </tr>
      <% end %>
    </table>
  </section>
<% else %>
  <h2> Top 20 Rated Movies </h2>

  <section id="movies_top_rated">
    <table>
      <caption hidden>Movies</caption>
      <tr>
        <th>Title</th>
        <th>Vote Avg</th>
      </tr>
      <% @top_rated.each do |movie| %>
        <tr>
          <td><%= link_to movie.title, user_movie_path(@user.id, movie.id) %></td>
          <td><%= movie.vote_avg %></td>
        </tr>
      <% end %>
    </table>
  </section>
<% end %>

MOD THREE/viewing_party_lite/app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

<%= button_to "Create Viewing Party for #{@movie.title}", new_user_movie_view_party_path(@user.id, @movie.id), method: :get %>
<%= button_to "Return to Discover Movies",  user_discoveries_path(@user.id), method: :get %>

<p>Vote Average: <%= @movie.vote_avg %></p>
<p>Runtime: <%= @movie.time_conversion %></p>
<p>Genre: <%= @movie.all_genres %></p>
<p>Summary: <%= @movie.summary %></p>
<section id="cast">
<ul>Cast: <% @cast.each do |actor| %>
  <li>Actor: <%= actor.name %>, Character: <%= actor.character %></li>
<% end %>
</ul>
</section>

<section id="reviews">
<h3><%=@reviews.count%> Reviews</h3>
  <% @reviews.each do |review| %>
    <p>Author: <%= review.author %></p>
    <p>Author's Review: <%= review.content %>/<p>
  <% end %>
</section>