MOD THREE/the_last_airbender_2210/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/search', to: 'search#index'
end

MOD THREE/the_last_airbender_2210/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MOD THREE/the_last_airbender_2210/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

MOD THREE/the_last_airbender_2210/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @nation_search = params[:nation]
    # require 'pry'; binding.pry

   conn =  Faraday.new(url:'https://last-airbender-api.fly.dev')
   response = conn.get('/api/v1/characters?affiliation=FIRE+NATION') #do |req|
    # req.params[] = term
    
   ### this isn't right it is only going to give fire nation information###
  #  response = conn.get('/api/v1/characters?affiliation=NATION+NAME')
  require 'pry'; binding.pry
   data = JSON.parse(response.body, symbolize_names: true)
   nation_list = data.first(25)
   @nations = [nation_list]

  end

end

MOD THREE/the_last_airbender_2210/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

MOD THREE/the_last_airbender_2210/app/helpers/application_helper.rb
module ApplicationHelper
    def element_nation
    [
      ['Air Nomads', 'air+nomads'],
      ['Earth Kingdom', 'earth+kingdom'],
      ['Fire Nation', 'fire+nation'],
      ['Water Tribes', 'water+tribes'],
    ]
  end
end

MOD THREE/the_last_airbender_2210/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LastAirbender</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

MOD THREE/the_last_airbender_2210/app/views/welcome/index.html.erb
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <p class ="navbar-brand">The Four Nations</p>
      <p class="subtitle">Search For Members by their Nation</p>
    </div>
    <div class="airbender-container">
      <%= image_tag("avatar.jpg", class: "airbender") %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= form_tag(search_path, method: "get") do %>
          <%= select_tag(:nation, options_for_select(element_nation), {class: "select-field"}) %>
          <%= submit_tag('Search For Members', class: "button") %>
        <% end %>
      </ul>
    </div>
  </nav>